codecov:
  token: f6004578-8b3d-4366-bcea-c229423ba532

coverage:
  precision: 2
  round: down
  range: "90...100"
  status:
    project:
      default:
        target: auto
        threshold: 2.0%
        informational: true
